#!/bin/bash

### Instructions to myself:
#Before running: ssh into cluster and copy all files (plink and pheno/covariate files) to /cluster/projects/p1531/moba_gwas/data/

#Run with typing 'sbatch JobScriptPlink'


### Instructions to queue system: ###
#SBATCH --job-name=full_gwas_plink
#SBATCH --account=p1531_tsd
#SBATCH --time=00:30:00 	#Wall-clock limit
#SBATCH --mem-per-cpu=500MB 	#Max memory usage
#SBATCH --cpus-per-task=1
#SBATCH --output=array_%A-%a.out
#SBATCH --array=1


#Clear inherited modules and load software
module purge
module load plink2/2.00a2LM


#Permanent paths for script, data and results
submit=$(pwd -P) #Get path to submit folder on cluster
dump=$submit'/../results' #Folder exists already
datdir='/cluster/projects/p1531/moba_gwas/data_plink'

#Clean up at error and put results in dump folder when finished or if anything goes wrong
set -o errexit
export results=$(date +%Y%m%d)'_GWAS_Mo_plink'
cleanup "cp -r $SCRATCH/$results $dump/"

#Move to SCRATCH, create temporary folders for data and results
cd $SCRATCH
mkdir $results
mkdir 'dat'

#Copy all input files and scripts to SCRATCH folders
cp -r $datdir dat/
cp $submit'/run_gwas_plink.sh' $results

### Run GWAS: ###
cd $results
declare -a commands

commands[1]="bash run_gwas_plink.sh Mo 1"
commands[2]="bash run_gwas_plink.sh Mo 2"
commands[3]="bash run_gwas_plink.sh Mo 3"
commands[4]="bash run_gwas_plink.sh Mo 4"
commands[5]="bash run_gwas_plink.sh Mo 5"
commands[6]="bash run_gwas_plink.sh Mo 6"
commands[7]="bash run_gwas_plink.sh Mo 7"
commands[8]="bash run_gwas_plink.sh Mo 8"
commands[9]="bash run_gwas_plink.sh Mo 9"
commands[10]="bash run_gwas_plink.sh Mo 10"
commands[11]="bash run_gwas_plink.sh Mo 11"
commands[12]="bash run_gwas_plink.sh Mo 12"
commands[13]="bash run_gwas_plink.sh Mo 13"
commands[14]="bash run_gwas_plink.sh Mo 14"
commands[15]="bash run_gwas_plink.sh Mo 15"
commands[16]="bash run_gwas_plink.sh Mo 16"
commands[17]="bash run_gwas_plink.sh Mo 17"
commands[18]="bash run_gwas_plink.sh Mo 18"
commands[19]="bash run_gwas_plink.sh Mo 19"
commands[20]="bash run_gwas_plink.sh Mo 20"
commands[21]="bash run_gwas_plink.sh Mo 21"
commands[22]="bash run_gwas_plink.sh Mo 22"
commands[23]="bash run_gwas_plink.sh Mo X"

#commands[]="bash run_gwas_plink.sh As 1"

bash -c "${commands[${SLURM_ARRAY_TASK_ID}]}"
